### ISSUE TITLE
Docker: No module named 'rescore'

### ISSUE THREAD

**Issue by i55code** [EdinburghNLP/nematus#108]
Hi Nematus team, 

I am using the docker for factored NMT and realized that there is a bug when I call python3 -c 'import nematus': 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nematus-0.4-py3.5.egg/nematus/__init__.py", line 2, in <module>
ImportError: No module named 'rescore'

Thanks, feel free to let me know what could be changed. Thanks!

**Comment by rsennrich** [comment]
thanks for reporting this; this should be fixed in commit abd71c4aef0f10156c07ddd74047d28662891a68
