### ISSUE TITLE
OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index -1 of dimension 1 out of bounds.

### ISSUE THREAD

**Issue by luou-wen** [EdinburghNLP/nematus#125]
Hello,
I am getting the following error when running nematus/translate.py using a transformer model:

2021-09-28 08:12:47.875696: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index -1 of dimension 1 out of bounds.
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/nematus/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/ec2-user/anaconda3/envs/nematus/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/ec2-user/anaconda3/envs/nematus/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: slice index -1 of dimension 1 out of bounds.
         [[{{node beam_search/model_adapter_0/strided_slice_169}}]]
         [[beam_search/truediv/_719]]
  (1) Invalid argument: slice index -1 of dimension 1 out of bounds.
         [[{{node beam_search/model_adapter_0/strided_slice_169}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/models/nematus//nematus/translate.py", line 125, in <module>
    main(settings)
  File "/home/ec2-user/models/nematus//nematus/translate.py", line 121, in main
    maxibatch_size=settings.maxibatch_size)
  File "/home/ec2-user/models/nematus/nematus/translate_utils.py", line 167, in translate_file
    translate_maxibatch(maxibatch, num_to_target, num_translated)
  File "/home/ec2-user/models/nematus/nematus/translate_utils.py", line 126, in translate_maxibatch
    max_translation_len, normalization_alpha)
  File "/home/ec2-user/models/nematus/nematus/translate_utils.py", line 67, in translate_batch
    translations, scores = session.run(sampler.outputs, feed_dict=feed_dict)
  File "/home/ec2-user/anaconda3/envs/nematus/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/ec2-user/anaconda3/envs/nematus/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ec2-user/anaconda3/envs/nematus/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/ec2-user/anaconda3/envs/nematus/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: slice index -1 of dimension 1 out of bounds.
         [[{{node beam_search/model_adapter_0/strided_slice_169}}]]
         [[beam_search/truediv/_719]]                                                                                                                         
  (1) Invalid argument: slice index -1 of dimension 1 out of bounds.
         [[{{node beam_search/model_adapter_0/strided_slice_169}}]]

**Comment by rsennrich** [comment]
thanks for reporting this. I wasn't immediately able to reproduce this, but this turned out to be a problem if translation_maxlen during inference (translate.py) was higher than at training time, because the Transformer's positional embeddings were only created up to the maxlen in the model config.

This is fixed now.

**Comment by luou-wen** [comment]
thank you very much!
