### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by BattsetsegB** [EdinburghNLP/nematus#93]
When i ran test_train.sh,appears this error.How to handle it? pls help. my env. is 
cuda8/cudnn5.1/tf-1.2

(venv) zhen@zhen-Lenovo:~/nematus/test$ CUDA_VISIBLE_DEVICES=0 ./test_train.sh
Traceback (most recent call last):
  File "../nematus/train.py", line 349, in <module>
    config = read_config_from_cmdline()
  File "/home/zhen/nematus/nematus/config.py", line 737, in read_config_from_cmdline
    param.derivation_func(config, meta_config))
  File "/home/zhen/nematus/nematus/config.py", line 977, in _derive_valid_source_dataset
    assert config.valid_datasets is not None
AssertionError

**Comment by BattsetsegB** [comment]
thanks,it fixed. sorry also i have a question. My output is looklike this screenshot. my question is, "model.npz-500.data-00000-of-00001" file is ouput trained model? where is model.npz-500 ?
![modeltf](https://user-images.githubusercontent.com/44496085/49938003-778d2380-ff13-11e8-9222-39c8f7b149e7.png)

**Comment by pjwilliams** [comment]
In TensorFlow a model checkpoint is made up of several files that share a prefix (which is used to refer to the model as a whole). So 'model.npz-500' is actually three files: model.npz-500.data-00000-of-00001, model.npz-500.index, and model.npz-500.meta (model.npz-500.progress.json is  a Nematus file containing additional information for that model).

**Comment by BattsetsegB** [comment]
Hi,  sorry also i have a question it is unclear to me on how to create `vocab_source.json` and `vocab_target.json` for my own dataset.

**Comment by rsennrich** [comment]
to create the network vocabulary files, use `data/build_dictionary.py`.

More generally, the recommended preprocessing steps are shown in the scripts shared in `http://data.statmt.org/wmt17_systems/training/`
