### ISSUE TITLE
None exception

### ISSUE THREAD

**Issue by Avmb** [EdinburghNLP/nematus#97]
When running /fs/meili0/amiceli/wmt-19-gu-en/run1/scripts/train.py I got

[...]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fs/meili0/amiceli/nematus-tf-transformer/nematus/train.py", line 385, in <module>
    train(config, sess)
  File "/fs/meili0/amiceli/nematus-tf-transformer/nematus/train.py", line 126, in train
    writer)
  File "/mnt/meili0/amiceli/nematus-tf-transformer/nematus/model_updater.py", line 43, in __init__
    global_step)
  File "/mnt/meili0/amiceli/nematus-tf-transformer/nematus/model_updater.py", line 355, in __init__
    self._define_accum_ops()
  File "/mnt/meili0/amiceli/nematus-tf-transformer/nematus/model_updater.py", line 424, in _define_accum_ops
    g) for g, v in summed_grad_vars]
  File "/mnt/meili0/amiceli/nematus-tf-transformer/nematus/model_updater.py", line 424, in <listcomp>
    g) for g, v in summed_grad_vars]
  File "/mnt/meili0/amiceli/tf-baldur-py3/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 190, in assign_add
    ref, value, use_locking=use_locking, name=name)
  File "/mnt/meili0/amiceli/tf-baldur-py3/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 107, in assign_add
    "AssignAdd", ref=ref, value=value, use_locking=use_locking, name=name)
  File "/mnt/meili0/amiceli/tf-baldur-py3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 529, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'value' to a tensor and failed. Error: None values not supported.

**Comment by rsennrich** [comment]
Hi Antonio,

this looks like a bug, but it's likely triggered by some more obscure code that isn't commonly used. Can you share your config (via e-mail is also fine)?

**Comment by rsennrich** [comment]
(thx for the config)

the bug triggered when training a deep transition RNN (--enc_recurrence_transition_depth 2), and has now been fixed.

**Comment by Avmb** [comment]
Thanks

**Comment by rsennrich** [comment]
c8f8a08 fixed --enc_recurrence_transition_depth, but --dec_base_recurrence_transition_depth is still broken.
